MVC/Taks2_MVC_IbraheemMaali/Models/Author.cs
namespace MVC_Project_BookStore.Models
{
    public class Author
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime CreatedOn { get; set; } = DateTime.Now;
        public DateTime UpdatedOn { get; set; } = DateTime.Now;
        //public List<Book> Books { get; set; } = new List<Book>();
    }
}

MVC/Taks2_MVC_IbraheemMaali/Controllers/AuthorsController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Project_BookStore.Data;
using MVC_Project_BookStore.Models;
using MVC_Project_BookStore.ViewModel;

namespace MVC_Project_BookStore.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly ApplicationDbContext context;

        public AuthorsController(ApplicationDbContext context)
        {
            this.context = context;
        }
        public IActionResult Index()
        {
            var result = context.authors.ToList();
            var authorsViewModel = new List<AuthorViewModel>();
            foreach (var author in result)
            {
                var authorViewModel = new AuthorViewModel()
                {
                    Id = author.Id,
                    Name = author.Name,
                    CreatedOn = author.CreatedOn,
                    UpdatedOn = author.UpdatedOn,
                };
                authorsViewModel.Add(authorViewModel);
            }
            return View("Index", authorsViewModel);
        }


        [HttpGet]
        public IActionResult Create()
        {

            return View("Form");
        }

        [HttpPost]
        public IActionResult Create(AuthorFormViewModel authorFormViewModel)
        {
            if (!ModelState.IsValid) // check if the input has errors like null
            {                        //  was you set  before to not accept null
                return View("Create", authorFormViewModel);
            }
            var author = new Author()
            {
                Name = authorFormViewModel.Name,
            };
            try
            {
                context.authors.Add(author);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                ModelState.AddModelError("Name", "author name already exists");
                return View("Create", authorFormViewModel);
            }
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {

            var author = context.authors.Find(id);
            if (author is null)
            {
                return NotFound();
            }
            var authorFormViewModel = new AuthorFormViewModel()
            {
                Id = id,
                Name = author.Name,
            };
            return View("Form", authorFormViewModel);
        }

        [HttpPost]
        public IActionResult Edit(AuthorFormViewModel authorFormViewModel)
        {
            if (!ModelState.IsValid) // check if the input has errors like null
            {                        //  was you set  before to not accept null
                return View("Form", authorFormViewModel);
            }
            var author = context.authors.Find(authorFormViewModel.Id);
            if (author is null)
            {
                return NotFound();
            }
            author.Name = authorFormViewModel.Name;
            author.UpdatedOn = DateTime.Now;
            context.SaveChanges();
            return RedirectToAction("Index");
        }


        public IActionResult Details(int id)
        {
            var author = context.authors.Find(id);
            if (author is null)
            {
                return NotFound();
            }
            var authorViewModel = new AuthorViewModel
            {
                Id = author.Id,
                Name = author.Name,
                CreatedOn = author.CreatedOn,
                UpdatedOn = author.UpdatedOn,
            };
            return View("Details", authorViewModel);
        }


        public IActionResult Delete(int id)
        {
            var author = context.authors.Find(id);
            if (author is null)
            {
                return NotFound();
            }

            context.authors.Remove(author);
            context.SaveChanges();
          
            return RedirectToAction("Index");
        }















    }

}

MVC/Taks2_MVC_IbraheemMaali/Views/Authors/Details.cshtml
@using MVC_Project_BookStore.ViewModel
@model AuthorViewModel


@section Title{
    Author Details
}
@section subTitle{
   Details
}


<div class="card-body">

    <table class="table table-bordered">
        <thead>
            <tr>
                <th style="width: 10px">#</th>
                <th>Name</th>
                <th>Created On</th>
                <th>Updated On</th>
            </tr>
        </thead>
        <tbody>

            <tr>
                <td>
                    @Model.Id
                </td>
                <td>
                    @Model.Name
                </td>
                <td>
                    @Model.CreatedOn
                </td>
                <td>
                    @Model.UpdatedOn
                </td>
            </tr>

        </tbody>
    </table>
</div>

MVC/Taks2_MVC_IbraheemMaali/Views/Authors/Form.cshtml
@using MVC_Project_BookStore.ViewModel
@model AuthorFormViewModel
@section Title{
    Categoriesc
}
@section subTitle{
    @(Model?.Id == null ? "Create" : "Edit")
}

<form asp-controller="Authors">

    <div class="card-body">
        <div class="form-group">

    

            <label asp-for="Name">Name</label>
            <input type="text" class="form-control" asp-for="Name" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>
    <div class="card-footer">
        <button typeof="submit" class="btn btn-primary">  @(Model?.Id == null ? "Add" : "Update")</button>

    </div>
</form>

MVC/Taks2_MVC_IbraheemMaali/Views/Authors/Index.cshtml
@using MVC_Project_BookStore.ViewModel;
@model List<AuthorViewModel>

@section Title{
    Authors
}
@section subTitle{
    Show
}

@section buttons{
    <a asp-controller="Authors" asp-action="Create" class="btn btn-primary">Create</a>
}

@if (!Model.Any())
{
    <div class="card-body">
        <div class="alert alert-warning alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h5><i class="icon fas fa-exclamation-triangle"></i> Alert!</h5>
            No data Found

        </div>
    </div>
}

else
{
    <div class="card-body">

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th style="width: 10px w-25" class="text-center">#</th>
                    <th class="text-center w-50">Name</th>
                    <th class="text-center w-25">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in @Model)
                {
                    <tr>
                        <td class="text-center">
                            @item.Id
                        </td>
                        <td class="text-center">
                            @item.Name
                        </td class="text-center">
                        <td class="d-flex justify-content-around">
                            <a asp-controller="Authors" asp-action="Edit" asp-route-id="@item.Id" class="btn bg-warning"><i class="fas fa-edit"></i> Edit</a>
                            <a asp-controller="Authors" asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary"><i class="fas fa-info"></i> Details</a>
                            <a asp-controller="Authors" asp-action="Delete" asp-route-id="@item.Id" class="btn bg-danger"><i class="fas fa-trash"></i> Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}

       @section scripts{
     <script> 
  const Toast = Swal.mixin({
  toast: true,
  position: 'top-end',
  iconColor: 'green',
  customClass: {
    popup: 'colored-toast',
  },
  showConfirmButton: false,
  timer: 1500,
  timerProgressBar: true,
})


      const elements=document.querySelectorAll(".js-delete");
     for(let ele of elements){
     ele.addEventListener("click", ()=>{
              console.log("hi");
              let id=ele.dataset.id;
              console.log(id);
               Swal.fire({
  title: "Do you want to Delete the categoy?",
  showDenyButton: true,
  showCancelButton: true,
  confirmButtonText: "Delete",
  denyButtonText: `Don't Delete`
}).then(async(result) => {
  /* Read more about isConfirmed, isDenied below */
  if (result.isConfirmed) {
      const response=await fetch(`/Authors/Delete/${id}`,{
                  method:"Post"
              })

              if(response.ok){
            ele.closest("tr").remove();
             //Swal.fire("Deleted!", "", "success");

             (async () => {
  await Toast.fire({
    icon: 'success',
    title: 'author deleted successfully!',
  })
  })()
              }
              else{
                   Swal.fire("Ooops....Author is not deleted , http 404 internal error", "", "info");
              }
  
  } else if (result.isDenied) {
    Swal.fire("Author is not deleted", "", "info");
  }
});
          })
      } 
   </script> ;
} 