MVC/Taks2_MVC_IbraheemMaali/Models/Book.cs
using System.ComponentModel.DataAnnotations;

namespace MVC_Project_BookStore.Models
{
    public class Book
    {
        public int Id { get; set; }
        [MaxLength(50)]
        public string Title { get; set; } = null!;
        public int AuthorId { get; set; }
        public Author Author { get; set; }
        public string Publisher { get; set; } = null!;
        public DateTime PublishDate { get; set; }
        public string? ImageUrl { get; set; } // in database , we want to store the name of image
        public string Description { get; set; } = null!;
        public DateTime CreatedOn { get; set; } = DateTime.Now;
        public DateTime UpdatedOn { get; set; } = DateTime.Now;
        public List<BookCategory> Categories { get; set; }=new List<BookCategory>();


    }
}

MVC/Taks2_MVC_IbraheemMaali/Controllers/BooksController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_Project_BookStore.Data;
using MVC_Project_BookStore.Models;
using MVC_Project_BookStore.ViewModel;
using System.Reflection.Metadata.Ecma335;

namespace MVC_Project_BookStore.Controllers
{
    public class BooksController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly IWebHostEnvironment webHostEnvironment;

        public BooksController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            this.context = context;
            this.webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            var books = context.books.
                Include(b => b.Author).//This tells Entity Framework to include the Author related data when querying the books table (Join)
                Include(b => b.Categories).
                ThenInclude(b => b.Category). // to include the category inside categories list
                ToList();
            //foreach (var book in books)
            //{
            //    Console.WriteLine($" {book.Author.Name}"); 

            //    foreach(var category in book.Categories)
            //    {
            //        Console.WriteLine($"{category.Category.Name}");
            //    }
            //}


            var bookViewModels = books.Select(book => new BookViewModel
            {
                Id = book.Id,
                Title = book.Title,
                Author = book.Author.Name,
                Publisher = book.Publisher,
                PublishDate = book.PublishDate,
                ImageUrl = book.ImageUrl,
                categories = book.Categories.Select(category => category.Category.Name).ToList()
            }).ToList();


            //var bookViewModels=new List<BookViewModel>();

            //foreach(var book in books)
            //{
            //    var bookViewModel = new BookViewModel()
            //    {
            //        Id = book.Id,
            //        Title = book.Title,
            //        Author = book.Author.Name,
            //        Publisher = book.Publisher,
            //        PublishDate = book.PublishDate,
            //        ImageUrl = book.ImageUrl,
            //        categories = new List<string>()
            //    };

            //    foreach (var category in book.Categories)
            //    {
            //        bookViewModel.categories.Add(category.Category.Name);
            //    }
            //    bookViewModels.Add(bookViewModel);
            //}

            return View(bookViewModels);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var authors = context.authors.OrderBy(author => author.Name).ToList();
            var authorList = new List<SelectListItem>();

            foreach (var author in authors)
            {
                authorList.Add(new SelectListItem
                {
                    Value = author.Id.ToString(),
                    Text = author.Name
                }
                );
            }


            var categories = context.categories.OrderBy(category => category.Name).ToList();
            var categoryList = new List<SelectListItem>();

            foreach (var category in categories)
            {
                categoryList.Add(new SelectListItem
                {
                    Value = category.Id.ToString(),
                    Text = category.Name
                }
                );
            }

            var viewModel = new BookFormViewModel
            {
                Authors = authorList,
                Categories = categoryList
            };
            return View(viewModel);
        }


        [HttpPost]
        public IActionResult Create(BookFormViewModel bookFormViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("Create");

            }

            var imageName = "";
            if (bookFormViewModel != null)
            {
                imageName = Path.GetFileName(bookFormViewModel.ImageUrl.FileName); // to get the name of the uploaded image

                //return Content($"{imageName}");

                //var path = Path.Combine($"{webHostEnvironment.WebRootPath}"); // here the path is up to wwwroot only
                var path = Path.Combine($"{webHostEnvironment.WebRootPath}/images/books", imageName);

                //return Content($"{path}");//D:\أكاديمية المعرفة\Full stack\Backend\ASP.net\MVC\myCoding\MVC_Project_BookStore\
                //                          //MVC_Project_BookStore\wwwroot/images/books\myImage.jpeg

                var stream = System.IO.File.Create(path); // the image when uploaded will be stored in temprory location
                                                          // so here we will move it to the path 

                bookFormViewModel.ImageUrl.CopyTo(stream); // move the image from temp location to the specified path (stream)

            }

            var book = new Book()
            {
                ImageUrl = imageName,
                Title = bookFormViewModel.Title,
                AuthorId = bookFormViewModel.AuthorId,
                Publisher = bookFormViewModel.Publisher,
                PublishDate = bookFormViewModel.PublishDate,
                Description = bookFormViewModel.Description,

                Categories = bookFormViewModel.SelectedCategories.Select(id => new BookCategory
                {
                    CategoryId = id,
                }).ToList(),
            };



            context.books.Add(book);
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var book = context.books.Find(id);
            if(book == null)
            {
                return NotFound();
            }
           
            var path = Path.Combine($"{webHostEnvironment.WebRootPath}/images/books", book.ImageUrl);

            if(System.IO.File.Exists(path)) // check if the image is exist
            {
                System.IO.File.Delete(path);
            }
               

            context.books.Remove(book);
            context.SaveChanges(true);

            return RedirectToAction("Index");
        }


    }
}

MVC/Taks2_MVC_IbraheemMaali/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using MVC_Project_BookStore.Data;
using MVC_Project_BookStore.Models;
using MVC_Project_BookStore.ViewModel;

namespace MVC_Project_BookStore.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext context;

        public CategoriesController(ApplicationDbContext context)
        {
            this.context = context;
        }
        public IActionResult Index()
        {
            var result = context.categories.ToList();
            return View(result);
        }
        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public IActionResult Create(CategoryViewModel categoryViewModel)
        {
            if (!ModelState.IsValid) // check if the input has errors like null
            {                        //  was you set  before to not accept null
                return View("Create", categoryViewModel);
            }
            var category = new Category
            {
                Name = categoryViewModel.Name,
            };
            try { 
            context.categories.Add(category);
             context.SaveChanges();
             return RedirectToAction("Index");
            }
            catch
            {
                ModelState.AddModelError("Name","category name already exists");
                return View("Create", categoryViewModel);
            }
          
            

        }


        [HttpGet]
        public IActionResult Edit(int id)
        {

            var category = context.categories.Find(id);
            if (category is null)
            {
                return NotFound();
            }
            var categoryViewModel = new CategoryViewModel
            {
                Id = id,
                Name = category.Name,
            };
            return View("Create", categoryViewModel);
        }

        [HttpPost]
        public IActionResult Edit(CategoryViewModel categoryViewModel)
        {
            if (!ModelState.IsValid) // check if the input has errors like null
            {                        //  was you set  before to not accept null
                return View("Create", categoryViewModel);
            }
            var category = context.categories.Find(categoryViewModel.Id);
            if (category is null)
            {
                return NotFound();
            }
            category.Name = categoryViewModel.Name;
            category.UpdatedOn= DateTime.Now;
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            var category = context.categories.Find(id);
            if (category is null)
            {
                return NotFound();
            }
            var categoryViewModel = new CategoryViewModel
            {
                Id = category.Id,
                Name = category.Name,
                CreatedOn = category.CreatedOn,
            UpdatedOn= category.UpdatedOn,
            };
            return View("Details",categoryViewModel);
        }

      
        public IActionResult Delete(int id)
        {
            var category = context.categories.Find(id);
            if (category is null)
            {
                return NotFound();
            }
          
            context.categories.Remove(category);
            context.SaveChanges();
            return Ok();
            //return RedirectToAction("Index");
        }
           

       public IActionResult checkName(CategoryViewModel categoryViewModel)
        {
            var isExists = context.categories.Any(category => category.Name == categoryViewModel.Name);
            return Json(!isExists);
        }








        }
}

MVC/Taks2_MVC_IbraheemMaali/Views/Books/Create.cshtml
@using MVC_Project_BookStore.ViewModel
@model BookFormViewModel
@section Title{
    Books
}
@section subTitle{
   Create
}

<form asp-controller="Books" asp-action="Create" enctype="multipart/form-data">

    <div class="card-body">

        <div class="form-group">
        <label asp-for="Title">Title</label>
        <input type="text" class="form-control" asp-for="Title" />
        <span asp-validation-for="Title" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="AuthorId"></label>
            <select asp-for="AuthorId" class="form-control" asp-items="@Model.Authors"></select>
            <span asp-validation-for="AuthorId" class="text-danger"></span>
        </div>

                <div class="form-group">
            <label asp-for="Publisher">Publisher</label>
            <input type="text" class="form-control" asp-for="Publisher" />
            <span asp-validation-for="Publisher" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="PublishDate"></label>
            <input type="date" class="form-control" asp-for="PublishDate" />
            <span asp-validation-for="PublishDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ImageUrl"></label>
            <input type="file" class="form-control" asp-for="ImageUrl" />
            <span asp-validation-for="ImageUrl" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Description">Description</label>
            <textarea asp-for="Description"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>


        <div class="form-group">
            <label asp-for="SelectedCategories"></label>
            <select asp-for="SelectedCategories" class="form-control" asp-items="@Model.Categories"></select>
            <span asp-validation-for="SelectedCategories" class="text-danger"></span>
        </div>





    </div>
    <div class="card-footer">
        <button type="submit" class="btn btn-primary">  Add </button>

    </div>
</form>

MVC/Taks2_MVC_IbraheemMaali/Views/Books/Index.cshtml
@using MVC_Project_BookStore.ViewModel;
@model List<BookViewModel>

@section Title{
    Books
}
@section subTitle{
   Show
}

@section buttons{
    <a asp-controller="Books" asp-action="Create" class="btn btn-primary">Create</a>
}


@if (!Model.Any())
{
    <div class="card-body">
        <div class="alert alert-warning alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h5><i class="icon fas fa-exclamation-triangle"></i> Alert!</h5>
            No data Found

        </div>
    </div>
}

else
{
    <div class="card-body">

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th style="" class="text-center">#</th>
                    <th >Title</th>
                    <th >Author</th>
                    <th >Publisher</th>
                     <th >PublishDate</th>
                      <th >ImageUrl</th>
                       <th >Categories</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in @Model) 
                {
                    <tr>
                        <td class="text-center">
                            @item.Id
                        </td>
                        <td class="text-center">
                            @item.Title
                        </td>
                        <td class="text-center">
                            @item.Author
                        </td>
                          <td class="text-center">
                            @item.Publisher
                        </td>
                        
                        <td class="text-center">
                        @item.PublishDate
                        </td>
                        <td class="text-center">
                           @* @item.ImageUrl*@
                            <img class="w-25 img-fluid" src="~/images/books/@item.ImageUrl" />
                        </td>
                        <td>
                            @string.Join(", ", @item.categories) <!-- convert  list to string--> 
                        </td>

                        <td class="d-flex justify-content-around">
                            <a asp-controller="Categories" asp-action="Edit" asp-route-id="@item.Id" class="btn bg-warning"><i class="fas fa-edit"></i> Edit</a>
                            <a asp-controller="Categories" asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary"><i class="fas fa-info"></i> Details</a>
                            <a asp-controller="Books" asp-action="Delete" asp-route-id="@item.Id" class="btn bg-danger"><i class="fas fa-trash"></i> Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}